# REAX potential for Nitroamines system
# .....

units		real

atom_style	charge
read_data	data.AB

pair_style	reax/c lmp_control
pair_coeff	* * ffield.reax.AB H B N

neighbor	2 bin
neigh_modify	every 10 delay 0 check no

fix		1 all nve
fix             2 all qeq/reax 1 0.0 10.0 1e-6 param.qeq
fix             3 all temp/berendsen 500.0 500.0 100.0

timestep	0.25

dump		1 all atom 30 dump.reax.ab

run		3000
