#!/bin/sh

if [ $TRILINOS_HOME ]; then
  echo "TRILINOS_HOME has already been set!"
else
  echo "TRILINOS_HOME has not been set.  Setting it!"
  export TRILINOS_HOME=`pwd`/../../..
fi

echo
echo "Generating main Kokkos doxygen documentation ..."
echo

doxygen Doxyfile

