/* ----------------------------------------------------------------------
   LAMMPS - Large-scale Atomic/Molecular Massively Parallel Simulator
   https://www.lammps.org/, Sandia National Laboratories
   LAMMPS Development team: developers@lammps.org

   Copyright (2003) Sandia Corporation.  Under the terms of Contract
   DE-AC04-94AL85000 with Sandia Corporation, the U.S. Government retains
   certain rights in this software.  This software is distributed under
   the GNU General Public License.

   See the README file in the top-level LAMMPS directory.
------------------------------------------------------------------------- */

// Tests for the "vtk" dump style.  The layout of the individual files is
// already checked by the VTKWriter tests, so these concentrate on what the
// dump style adds on top of it: selecting the file format from the file name
// extension, the extra file with the box dimensions, the naming and grouping
// of the atom attributes, and the file names for per timestep and per
// processor output.

#include "../testing/core.h"
#include "../testing/systems/melt.h"
#include "../testing/utils.h"
#include "fmt/format.h"
#include "utils.h"
#include "gmock/gmock.h"
#include "gtest/gtest.h"

#include <cstdint>
#include <cstring>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

using ::testing::Eq;
using ::testing::HasSubstr;
using ::testing::Not;

bool verbose = false;

namespace LAMMPS_NS {

// read a whole file, including the null bytes of binary data

static std::string slurp(const std::string &filename)
{
    std::ifstream in(filename, std::ios::binary);
    std::ostringstream buf;
    buf << in.rdbuf();
    return buf.str();
}

// pull the numbers between the first ">" after "marker" and the following "<"

static std::vector<double> xml_payload(const std::string &text, const std::string &marker)
{
    auto pos = text.find(marker);
    if (pos == std::string::npos) return {};
    pos = text.find('>', pos);
    if (pos == std::string::npos) return {};
    const auto end = text.find('<', pos);

    std::istringstream in(text.substr(pos + 1, end - pos - 1));
    std::vector<double> values;
    double v;
    while (in >> v)
        values.push_back(v);
    return values;
}

// legacy binary files store their data in big endian byte order

template <typename T> static T read_be(const char *p)
{
    const int one = 1;
    char buf[sizeof(T)];
    if (*((const char *)&one) == 1) {
        for (std::size_t i = 0; i < sizeof(T); ++i)
            buf[i] = p[sizeof(T) - 1 - i];
    } else {
        memcpy(buf, p, sizeof(T));
    }
    T v;
    memcpy(&v, buf, sizeof(T));
    return v;
}

class DumpVTKTest : public MeltTest {
public:
    void enable_triclinic()
    {
        BEGIN_HIDE_OUTPUT();
        command("change_box all triclinic");
        END_HIDE_OUTPUT();
    }

    void generate_dump(const std::string &dump_file, const std::string &fields,
                       const std::string &dump_modify_options, int ntimesteps)
    {
        BEGIN_HIDE_OUTPUT();
        command(fmt::format("dump id all vtk 1 {} {}", dump_file, fields));

        if (!dump_modify_options.empty()) {
            command(fmt::format("dump_modify id {}", dump_modify_options));
        }

        command(fmt::format("run {} post no", ntimesteps));
        END_HIDE_OUTPUT();
    }
};

//-------------------------------------------------------------------------------------------------
// legacy VTK format
//-------------------------------------------------------------------------------------------------

TEST_F(DumpVTKTest, legacy_run0)
{
    const std::string dump_file = "dump_vtk_run0.vtk";
    const std::string box_file  = "dump_vtk_run0_boundingBox.vtk";
    generate_dump(dump_file, "id type", "sort id", 0);

    ASSERT_FILE_EXISTS(dump_file);
    auto lines = read_lines(dump_file);
    ASSERT_GT(lines.size(), 5);
    ASSERT_THAT(lines[0], Eq("# vtk DataFile Version 5.1"));
    ASSERT_THAT(lines[1], Eq("Generated by LAMMPS"));
    ASSERT_THAT(lines[2], Eq("ASCII"));
    ASSERT_THAT(lines[3], Eq("DATASET POLYDATA"));
    ASSERT_THAT(lines[4], Eq("POINTS 32 float"));

    auto text = slurp(dump_file);

    // one vertex cell per atom, so there is one offset more than atoms

    EXPECT_THAT(text, HasSubstr("VERTICES 33 32\n"));

    // the attributes become field data in the order of the dump command

    EXPECT_THAT(text, HasSubstr("POINT_DATA 32\nFIELD FieldData 2\n"));
    EXPECT_THAT(text, HasSubstr("id 1 32 int\n1 2 3 4 5 6 7 8 9\n"));
    EXPECT_THAT(text, HasSubstr("type 1 32 int\n1 1 1 1 1 1 1 1 1\n"));

    // the box dimensions go into a second file

    ASSERT_FILE_EXISTS(box_file);
    auto box = slurp(box_file);
    EXPECT_THAT(box, HasSubstr("DATASET RECTILINEAR_GRID\nDIMENSIONS 2 2 2\n"));
    EXPECT_THAT(box, HasSubstr("X_COORDINATES 2 float\n0 3.359"));
    EXPECT_THAT(box, HasSubstr("Y_COORDINATES 2 float\n0 3.359"));
    EXPECT_THAT(box, HasSubstr("Z_COORDINATES 2 float\n0 3.359"));

    delete_file(dump_file);
    delete_file(box_file);
}

TEST_F(DumpVTKTest, legacy_attributes)
{
    const std::string dump_file = "dump_vtk_attributes.vtk";
    const std::string box_file  = "dump_vtk_attributes_boundingBox.vtk";

    // x, y, z are always written as the point coordinates, duplicate
    // attributes are dropped, and the three components of a vector attribute
    // are combined into a single array named after the attribute

    generate_dump(dump_file, "vx vy vz id id type x y z fx fy fz element mass", "sort id", 0);

    ASSERT_FILE_EXISTS(dump_file);
    auto text = slurp(dump_file);
    EXPECT_THAT(text, HasSubstr("POINTS 32 float\n"));
    EXPECT_THAT(text, HasSubstr("POINT_DATA 32\nFIELD FieldData 6\n"));
    EXPECT_THAT(text, HasSubstr("id 1 32 int\n1 2 3 4 5 6 7 8 9\n"));
    EXPECT_THAT(text, HasSubstr("type 1 32 int\n"));
    EXPECT_THAT(text, HasSubstr("element 1 32 string\nC\nC\n"));
    EXPECT_THAT(text, HasSubstr("mass 1 32 float\n"));
    EXPECT_THAT(text, HasSubstr("v 3 32 float\n"));
    EXPECT_THAT(text, HasSubstr("f 3 32 float\n"));
    EXPECT_THAT(text, Not(HasSubstr("x 1 32 float\n")));

    delete_file(dump_file);
    delete_file(box_file);
}

TEST_F(DumpVTKTest, legacy_element_names)
{
    const std::string dump_file = "dump_vtk_element.vtk";
    const std::string box_file  = "dump_vtk_element_boundingBox.vtk";
    generate_dump(dump_file, "id element", "element Ar sort id", 0);

    ASSERT_FILE_EXISTS(dump_file);
    EXPECT_THAT(slurp(dump_file), HasSubstr("element 1 32 string\nAr\nAr\n"));

    delete_file(dump_file);
    delete_file(box_file);
}

TEST_F(DumpVTKTest, legacy_binary_run0)
{
    const std::string dump_file = "dump_vtk_binary.vtk";
    const std::string box_file  = "dump_vtk_binary_boundingBox.vtk";
    generate_dump(dump_file, "id type", "binary yes label \"my title\" sort id", 0);

    ASSERT_FILE_EXISTS(dump_file);
    auto data = slurp(dump_file);
    EXPECT_THAT(data, HasSubstr("# vtk DataFile Version 5.1\nmy title\nBINARY\n"));
    EXPECT_THAT(data, Not(HasSubstr("\nASCII\n")));

    // coordinates are stored as big endian floats.  the first atom sits in
    // the lower left corner of the box.

    const std::string points = "POINTS 32 float\n";
    auto pos                 = data.find(points);
    ASSERT_NE(pos, std::string::npos);
    pos += points.size();
    for (int i = 0; i < 3; ++i)
        EXPECT_FLOAT_EQ(read_be<float>(data.data() + pos + 4 * i), 0.0);
    EXPECT_EQ(data.compare(pos + 32 * 3 * 4, 10, "\nVERTICES "), 0);

    // integer attributes are stored as big endian 32-bit integers

    const std::string ids = "id 1 32 int\n";
    pos                   = data.find(ids);
    ASSERT_NE(pos, std::string::npos);
    pos += ids.size();
    for (int i = 0; i < 32; ++i)
        EXPECT_EQ(read_be<std::int32_t>(data.data() + pos + 4 * i), i + 1);

    // the box file is written in binary as well and gets the same title

    ASSERT_FILE_EXISTS(box_file);
    EXPECT_THAT(slurp(box_file), HasSubstr("my title\nBINARY\nDATASET RECTILINEAR_GRID\n"));

    delete_file(dump_file);
    delete_file(box_file);
}

TEST_F(DumpVTKTest, unknown_extension_is_legacy)
{
    const std::string dump_file = "dump_vtk_unknown.melt";
    const std::string box_file  = "dump_vtk_unknown_boundingBox.melt";
    generate_dump(dump_file, "id type", "", 0);

    ASSERT_FILE_EXISTS(dump_file);
    EXPECT_THAT(slurp(dump_file), HasSubstr("# vtk DataFile Version 5.1\n"));
    EXPECT_THAT(slurp(dump_file), HasSubstr("DATASET POLYDATA\n"));

    ASSERT_FILE_EXISTS(box_file);
    EXPECT_THAT(slurp(box_file), HasSubstr("DATASET RECTILINEAR_GRID\n"));

    delete_file(dump_file);
    delete_file(box_file);
}

TEST_F(DumpVTKTest, legacy_triclinic_run0)
{
    const std::string dump_file = "dump_vtk_tri.vtk";
    const std::string box_file  = "dump_vtk_tri_boundingBox.vtk";
    enable_triclinic();
    generate_dump(dump_file, "id type", "", 0);

    ASSERT_FILE_EXISTS(dump_file);
    EXPECT_THAT(slurp(dump_file), HasSubstr("DATASET POLYDATA\nPOINTS 32 float\n"));

    // a triclinic box cannot be a rectilinear grid, it becomes a hexahedron
    // cell (VTK cell type 12) of an unstructured grid instead

    ASSERT_FILE_EXISTS(box_file);
    auto box = slurp(box_file);
    EXPECT_THAT(box, HasSubstr("DATASET UNSTRUCTURED_GRID\nPOINTS 8 float\n"));
    EXPECT_THAT(box, HasSubstr("CELLS 2 8\n"));
    EXPECT_THAT(box, HasSubstr("CELL_TYPES 1\n12 \n"));

    delete_file(dump_file);
    delete_file(box_file);
}

//-------------------------------------------------------------------------------------------------
// XML formats
//-------------------------------------------------------------------------------------------------

TEST_F(DumpVTKTest, xml_polydata_run0)
{
    const std::string dump_file = "dump_vtk_poly.vtp";
    const std::string box_file  = "dump_vtk_poly_boundingBox.vtr";
    generate_dump(dump_file, "id type vx vy vz", "sort id", 0);

    ASSERT_FILE_EXISTS(dump_file);
    auto text = slurp(dump_file);
    EXPECT_THAT(text, HasSubstr(R"(<VTKFile type="PolyData" version="0.1")"));
    EXPECT_THAT(text, HasSubstr(R"(<Piece NumberOfPoints="32" NumberOfVerts="32")"));
    EXPECT_THAT(text, HasSubstr(R"(<DataArray type="Int32" Name="id" format="ascii">)"));
    EXPECT_THAT(text, HasSubstr(R"(<DataArray type="Int32" Name="type" format="ascii">)"));
    EXPECT_THAT(text, HasSubstr(R"(<DataArray type="Float32" Name="v" NumberOfComponents="3")"));
    EXPECT_THAT(text,
                HasSubstr(R"(<DataArray type="Float32" Name="Points" NumberOfComponents="3")"));

    // the box file switches to the extension of the rectilinear grid format

    ASSERT_FILE_EXISTS(box_file);
    ASSERT_FILE_NOT_EXISTS("dump_vtk_poly_boundingBox.vtp");
    auto box = slurp(box_file);
    EXPECT_THAT(box, HasSubstr(R"(<VTKFile type="RectilinearGrid")"));
    EXPECT_THAT(box, HasSubstr(R"(<RectilinearGrid WholeExtent="0 1 0 1 0 1">)"));

    delete_file(dump_file);
    delete_file(box_file);
}

TEST_F(DumpVTKTest, xml_unstructured_run0)
{
    const std::string dump_file = "dump_vtk_grid.vtu";
    const std::string box_file  = "dump_vtk_grid_boundingBox.vtr";
    generate_dump(dump_file, "id type", "sort id", 0);

    ASSERT_FILE_EXISTS(dump_file);
    auto text = slurp(dump_file);
    EXPECT_THAT(text, HasSubstr(R"(<VTKFile type="UnstructuredGrid")"));
    EXPECT_THAT(text, HasSubstr(R"(<Piece NumberOfPoints="32" NumberOfCells="32">)"));
    EXPECT_THAT(text, HasSubstr(R"(<DataArray type="Int32" Name="id" format="ascii">)"));

    // each atom is written as a vertex cell (VTK cell type 1)

    EXPECT_EQ(xml_payload(text, R"(Name="types")"), std::vector<double>(32, 1.0));

    ASSERT_FILE_EXISTS(box_file);
    EXPECT_THAT(slurp(box_file), HasSubstr(R"(<VTKFile type="RectilinearGrid")"));

    delete_file(dump_file);
    delete_file(box_file);
}

TEST_F(DumpVTKTest, xml_binary_run0)
{
    const std::string dump_file = "dump_vtk_binary.vtp";
    const std::string box_file  = "dump_vtk_binary_boundingBox.vtr";
    generate_dump(dump_file, "id type", "binary yes", 0);

    ASSERT_FILE_EXISTS(dump_file);
    auto text = slurp(dump_file);
    EXPECT_THAT(text, HasSubstr(R"(<DataArray type="Int32" Name="id" format="binary">)"));
    EXPECT_THAT(text, HasSubstr(R"(Name="Points" NumberOfComponents="3" format="binary">)"));
    EXPECT_THAT(text, Not(HasSubstr(R"(format="ascii")")));

    ASSERT_FILE_EXISTS(box_file);
    EXPECT_THAT(slurp(box_file), HasSubstr(R"(format="binary")"));

    delete_file(dump_file);
    delete_file(box_file);
}

TEST_F(DumpVTKTest, xml_triclinic_run0)
{
    const std::string dump_file = "dump_vtk_tri.vtp";
    const std::string box_file  = "dump_vtk_tri_boundingBox.vtu";
    enable_triclinic();
    generate_dump(dump_file, "id type", "", 0);

    ASSERT_FILE_EXISTS(dump_file);
    EXPECT_THAT(slurp(dump_file), HasSubstr(R"(<VTKFile type="PolyData")"));

    // the box needs the unstructured grid format and thus its extension

    ASSERT_FILE_EXISTS(box_file);
    ASSERT_FILE_NOT_EXISTS("dump_vtk_tri_boundingBox.vtr");
    auto box = slurp(box_file);
    EXPECT_THAT(box, HasSubstr(R"(<VTKFile type="UnstructuredGrid")"));
    EXPECT_THAT(box, HasSubstr(R"(<Piece NumberOfPoints="8" NumberOfCells="1">)"));

    // the box is a single hexahedron cell (VTK cell type 12)

    EXPECT_EQ(xml_payload(box, R"(Name="types")"), std::vector<double>({12.0}));

    delete_file(dump_file);
    delete_file(box_file);
}

//-------------------------------------------------------------------------------------------------
// file names
//-------------------------------------------------------------------------------------------------

TEST_F(DumpVTKTest, multi_file_run1)
{
    generate_dump("dump_vtk_multi_*.vtk", "id type", "", 1);

    // one file per snapshot, and one box file to go with each of them

    for (const auto &step : {"0", "1"}) {
        auto dump_file = fmt::format("dump_vtk_multi_{}.vtk", step);
        auto box_file  = fmt::format("dump_vtk_multi_{}_boundingBox.vtk", step);
        ASSERT_FILE_EXISTS(dump_file);
        ASSERT_FILE_EXISTS(box_file);
        EXPECT_THAT(slurp(dump_file), HasSubstr("POINTS 32 float\n"));
        delete_file(dump_file);
        delete_file(box_file);
    }
}

TEST_F(DumpVTKTest, per_processor_polydata)
{
    // the "%" is replaced by the processor id preceded by an underscore and
    // rank 0 writes a summary file that lists the individual pieces

    generate_dump("dump_vtk_par_%.vtp", "id type element vx vy vz", "", 0);

    const std::string piece_file   = "dump_vtk_par__0.vtp";
    const std::string summary_file = "dump_vtk_par_.pvtp";
    const std::string box_file     = "dump_vtk_par__boundingBox.vtr";

    ASSERT_FILE_EXISTS(piece_file);
    ASSERT_FILE_EXISTS(summary_file);
    ASSERT_FILE_EXISTS(box_file);

    // the summary must declare the same arrays as the pieces contain

    auto summary = slurp(summary_file);
    EXPECT_THAT(summary, HasSubstr(R"(<VTKFile type="PPolyData" version="1.0")"));
    EXPECT_THAT(summary, HasSubstr(R"(<PDataArray type="Int32" Name="id"/>)"));
    EXPECT_THAT(summary, HasSubstr(R"(<PDataArray type="Int32" Name="type"/>)"));
    EXPECT_THAT(summary, HasSubstr(R"(<PDataArray type="String" Name="element"/>)"));
    EXPECT_THAT(summary,
                HasSubstr(R"(<PDataArray type="Float32" Name="v" NumberOfComponents="3"/>)"));
    EXPECT_THAT(summary,
                HasSubstr(R"(<PDataArray type="Float32" Name="Points" NumberOfComponents="3"/>)"));
    EXPECT_THAT(summary, HasSubstr(fmt::format(R"(<Piece Source="{}"/>)", piece_file)));

    delete_file(piece_file);
    delete_file(summary_file);
    delete_file(box_file);
}

TEST_F(DumpVTKTest, per_processor_multi_file_run1)
{
    generate_dump("dump_vtk_pm_%_*.vtu", "id type", "", 1);

    for (const auto &step : {"0", "1"}) {
        auto piece_file   = fmt::format("dump_vtk_pm__0_{}.vtu", step);
        auto summary_file = fmt::format("dump_vtk_pm__{}.pvtu", step);
        auto box_file     = fmt::format("dump_vtk_pm__{}_boundingBox.vtr", step);

        ASSERT_FILE_EXISTS(piece_file);
        ASSERT_FILE_EXISTS(summary_file);
        ASSERT_FILE_EXISTS(box_file);

        auto summary = slurp(summary_file);
        EXPECT_THAT(summary, HasSubstr(R"(<VTKFile type="PUnstructuredGrid" version="1.0")"));
        EXPECT_THAT(summary, HasSubstr(fmt::format(R"(<Piece Source="{}"/>)", piece_file)));

        delete_file(piece_file);
        delete_file(summary_file);
        delete_file(box_file);
    }
}

TEST_F(DumpVTKTest, legacy_has_no_per_processor_files)
{
    const std::string dump_file = "dump_vtk_pct_0.vtk";
    const std::string box_file  = "dump_vtk_pct_0_boundingBox.vtk";

    // the legacy format writes a single file with all atoms, so the "%" in
    // the file name becomes 0 instead of one file name per processor

    auto output = CAPTURE_OUTPUT([&] {
        command("dump id all vtk 1 dump_vtk_pct_%.vtk id type");
        command("run 0 post no");
    });
    EXPECT_THAT(output, HasSubstr("Cannot write one file per processor with the legacy VTK"));

    ASSERT_FILE_NOT_EXISTS("dump_vtk_pct_%.vtk");
    ASSERT_FILE_EXISTS(dump_file);
    ASSERT_FILE_EXISTS(box_file);
    EXPECT_THAT(slurp(dump_file), HasSubstr("POINTS 32 float\n"));

    delete_file(dump_file);
    delete_file(box_file);
}

TEST_F(DumpVTKTest, write_dump)
{
    const std::string reference = "dump_vtk_reference.vtp";
    const std::string dump_file = "dump_vtk_written.vtp";

    BEGIN_HIDE_OUTPUT();
    command(fmt::format("dump id all vtk 1 {} id type", reference));
    command("dump_modify id sort id");
    command("run 0 post no");
    command(fmt::format("write_dump all vtk {} id type modify sort id", dump_file));
    END_HIDE_OUTPUT();

    ASSERT_FILE_EXISTS(reference);
    ASSERT_FILE_EXISTS(dump_file);
    ASSERT_FILE_EQUAL(reference, dump_file);

    delete_file(reference);
    delete_file(dump_file);
    delete_file("dump_vtk_reference_boundingBox.vtr");
    delete_file("dump_vtk_written_boundingBox.vtr");
}

//-------------------------------------------------------------------------------------------------
// double precision output
//-------------------------------------------------------------------------------------------------

TEST_F(DumpVTKTest, double_precision_legacy)
{
    const std::string dump_file = "dump_vtk_double.vtk";
    const std::string box_file  = "dump_vtk_double_boundingBox.vtk";

    // dump_modify double yes switches all floating point data to double
    // precision, including the box file

    generate_dump(dump_file, "id vx vy vz", "double yes sort id", 0);

    ASSERT_FILE_EXISTS(dump_file);
    auto text = slurp(dump_file);
    EXPECT_THAT(text, HasSubstr("POINTS 32 double\n"));
    EXPECT_THAT(text, HasSubstr("v 3 32 double\n"));

    ASSERT_FILE_EXISTS(box_file);
    EXPECT_THAT(slurp(box_file), HasSubstr("X_COORDINATES 2 double\n"));

    delete_file(dump_file);
    delete_file(box_file);
}

TEST_F(DumpVTKTest, double_precision_xml)
{
    const std::string dump_file = "dump_vtk_double.vtp";
    const std::string box_file  = "dump_vtk_double_boundingBox.vtr";

    generate_dump(dump_file, "id vx vy vz", "double yes sort id", 0);

    ASSERT_FILE_EXISTS(dump_file);
    auto text = slurp(dump_file);
    EXPECT_THAT(text,
                HasSubstr(R"(<DataArray type="Float64" Name="Points" NumberOfComponents="3")"));
    EXPECT_THAT(text, HasSubstr(R"(<DataArray type="Float64" Name="v" NumberOfComponents="3")"));

    delete_file(dump_file);
    delete_file(box_file);
}

TEST_F(DumpVTKTest, double_precision_summary)
{
    // the per processor summary file has to declare the same types that the
    // piece files contain

    generate_dump("dump_vtk_dpar_%.vtp", "id vx vy vz", "double yes", 0);

    const std::string summary_file = "dump_vtk_dpar_.pvtp";
    ASSERT_FILE_EXISTS(summary_file);
    auto summary = slurp(summary_file);
    EXPECT_THAT(summary,
                HasSubstr(R"(<PDataArray type="Float64" Name="v" NumberOfComponents="3"/>)"));
    EXPECT_THAT(summary,
                HasSubstr(R"(<PDataArray type="Float64" Name="Points" NumberOfComponents="3"/>)"));

    delete_file("dump_vtk_dpar__0.vtp");
    delete_file(summary_file);
    delete_file("dump_vtk_dpar__boundingBox.vtr");
}

//-------------------------------------------------------------------------------------------------
// selecting a subset of the atoms
//-------------------------------------------------------------------------------------------------

TEST_F(DumpVTKTest, thresh)
{
    const std::string dump_file = "dump_vtk_thresh.vtk";
    const std::string box_file  = "dump_vtk_thresh_boundingBox.vtk";

    // the lattice has 8 atoms in each of its 4 layers along x

    generate_dump(dump_file, "id type", "thresh x < 1.7 sort id", 0);

    ASSERT_FILE_EXISTS(dump_file);
    auto text = slurp(dump_file);
    EXPECT_THAT(text, HasSubstr("POINTS 24 float\n"));
    EXPECT_THAT(text, HasSubstr("POINT_DATA 24\n"));
    EXPECT_THAT(text, HasSubstr("id 1 24 int\n"));

    delete_file(dump_file);
    delete_file(box_file);
}

TEST_F(DumpVTKTest, region)
{
    const std::string dump_file = "dump_vtk_region.vtp";
    const std::string box_file  = "dump_vtk_region_boundingBox.vtr";

    BEGIN_HIDE_OUTPUT();
    command("region left block INF 1.7 INF INF INF INF units box");
    END_HIDE_OUTPUT();
    generate_dump(dump_file, "id type", "region left sort id", 0);

    ASSERT_FILE_EXISTS(dump_file);
    EXPECT_THAT(slurp(dump_file), HasSubstr(R"(<Piece NumberOfPoints="24" NumberOfVerts="24")"));

    delete_file(dump_file);
    delete_file(box_file);
}

//-------------------------------------------------------------------------------------------------
// diagnostics and error messages
//-------------------------------------------------------------------------------------------------

TEST_F(DumpVTKTest, single_precision_warning)
{
    const std::string dump_file = "dump_vtk_precision.vtk";
    const std::string box_file  = "dump_vtk_precision_boundingBox.vtk";

    // coordinates are stored in single precision, which is fine for the melt
    // system but not for an atom 20000 length units away from the origin

    auto output = CAPTURE_OUTPUT([&] {
        command(fmt::format("write_dump all vtk {} id type", dump_file));
    });
    EXPECT_THAT(output, Not(HasSubstr("single precision")));

    BEGIN_HIDE_OUTPUT();
    command("set atom 1 x 20000.0");
    END_HIDE_OUTPUT();

    output = CAPTURE_OUTPUT([&] {
        command(fmt::format("write_dump all vtk {} id type", dump_file));
    });
    EXPECT_THAT(output, HasSubstr("Dump vtk writes atom coordinates in single precision"));

    // with double precision output there is nothing to warn about

    output = CAPTURE_OUTPUT([&] {
        command(fmt::format("write_dump all vtk {} id type modify double yes", dump_file));
    });
    EXPECT_THAT(output, Not(HasSubstr("single precision")));
    EXPECT_THAT(slurp(dump_file), HasSubstr("POINTS 32 double\n"));

    delete_file(dump_file);
    delete_file(box_file);
}

TEST_F(DumpVTKTest, invalid_attribute)
{
    TEST_FAILURE(".*Invalid attribute xxx in dump vtk command.*",
                 command("dump id all vtk 1 dump_vtk_invalid.vtk xxx"););
}

TEST_F(DumpVTKTest, no_attributes)
{
    TEST_FAILURE(".*No dump vtk arguments specified.*",
                 command("dump id all vtk 1 dump_vtk_invalid.vtk"););
}

TEST_F(DumpVTKTest, dump_modify_invalid)
{
    BEGIN_HIDE_OUTPUT();
    command("dump id all vtk 1 dump_vtk_invalid.vtk id type");
    END_HIDE_OUTPUT();

    TEST_FAILURE(".*Expected boolean parameter instead of 'xxx'.*",
                 command("dump_modify id binary xxx"););
    TEST_FAILURE(".*Expected boolean parameter instead of 'xxx'.*",
                 command("dump_modify id double xxx"););
    TEST_FAILURE(".*Illegal dump_modify double command: missing argument.*",
                 command("dump_modify id double"););
    TEST_FAILURE(".*Illegal dump_modify label command: missing argument.*",
                 command("dump_modify id label"););
    TEST_FAILURE(".*Number of dump_modify element names does not match number of atom types.*",
                 command("dump_modify id element"););
    TEST_FAILURE(".*Dump_modify region nosuchregion does not exist.*",
                 command("dump_modify id region nosuchregion"););
}
} // namespace LAMMPS_NS

int main(int argc, char **argv)
{
    MPI_Init(&argc, &argv);
    ::testing::InitGoogleMock(&argc, argv);

    // handle arguments passed via environment variable
    if (const char *var = getenv("TEST_ARGS")) {
        std::vector<std::string> env = LAMMPS_NS::utils::split_words(var);
        for (auto arg : env) {
            if (arg == "-v") {
                verbose = true;
            }
        }
    }

    if ((argc > 1) && (strcmp(argv[1], "-v") == 0)) verbose = true;

    int rv = RUN_ALL_TESTS();
    MPI_Finalize();
    return rv;
}
