# The packages the Tier-1 KOKKOS porting touches, and only those: pass this with
# -C to build the verification decks without paying for the full most.cmake set.
set(ALL_PACKAGES
  AMOEBA ASPHERE BOCS BODY BPM BROWNIAN CG-DNA CG-SPICA CLASS2 COLLOID COLVARS
  COMPRESS CORESHELL DIELECTRIC DIFFRACTION DIPOLE DPD-BASIC DPD-MESO DPD-REACT
  DPD-SMOOTH DRUDE EFF ELECTRODE EXTRA-COMMAND EXTRA-COMPUTE EXTRA-DUMP EXTRA-FIX
  EXTRA-MOLECULE EXTRA-PAIR FEP GRAPHICS GRANULAR GRANSURF INTERLAYER KSPACE
  LEPTON MACHDYN MANYBODY MC MEAM MESONT MISC ML-IAP ML-POD ML-SNAP ML-UF3 MOFFF
  MOLECULE OPENMP OPT ORIENT PERI PHONON PLUGIN QEQ REACTION REAXFF REPLICA RHEO
  RIGID SHOCK SPH SPIN SRD TALLY UEF VORONOI YAFF APIP)
foreach(PKG ${ALL_PACKAGES})
  set(PKG_${PKG} OFF CACHE BOOL "" FORCE)
endforeach()

set(TIER1_PACKAGES
  ASPHERE BROWNIAN CLASS2 COMPRESS CORESHELL DIPOLE EXTRA-COMPUTE EXTRA-FIX
  EXTRA-MOLECULE EXTRA-PAIR FEP GRANULAR KSPACE MANYBODY MISC MOLECULE RIGID SHOCK)
foreach(PKG ${TIER1_PACKAGES})
  set(PKG_${PKG} ON CACHE BOOL "" FORCE)
endforeach()
