# --- Running Moltemplate ---
#  -- Prerequisites: --
# The "system.lt" moltemplate file links to other ".lt" files
# files you hopefully have created earlier when you ran "ltemplify.py:
#    cnad.lt and cnt.lt
# If not, carry out the instructions in "README_run_ltemplify.sh".

moltemplate.sh system.lt

# This will generate various files with names ending in *.in* and *.data. 
# These files are the input files directly read by LAMMPS.

# Optional:
# The "./output_ttree/" directory is full of temporary files generated by 
# moltemplate.  They can be useful for debugging, but are usually thrown away.

rm -rf output_ttree/

