#!/bin/sh
echo="Apple LLVM version 8.1.0 (clang-802.0.42)"
echo="Target: x86_64-apple-darwin16.7.0"
echo="Thread model: posix"
echo="InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin"
