#!/bin/sh
echo "nvcc: NVIDIA (R) Cuda compiler driver"
echo "Copyright (c) 2005-2016 NVIDIA Corporation"
echo "Built on Tue_Jan_10_13:22:03_CST_2017"
echo "Cuda compilation tools, release 8.0, V8.0.61"
