# Install/unInstall package files in LAMMPS

if (test $1 = 1) then

  cp angle_charmm.cpp ..
  cp angle_cosine.cpp ..
  cp angle_cosine_delta.cpp ..
  cp angle_cosine_periodic.cpp ..
  cp angle_cosine_squared.cpp ..
  cp angle_harmonic.cpp ..
  cp angle_hybrid.cpp ..
  cp angle_table.cpp ..
  cp atom_vec_angle.cpp ..
  cp atom_vec_bond.cpp ..
  cp atom_vec_full.cpp ..
  cp atom_vec_molecular.cpp ..
  cp bond_fene.cpp ..
  cp bond_fene_expand.cpp ..
  cp bond_harmonic.cpp ..
  cp bond_morse.cpp ..
  cp bond_nonlinear.cpp ..
  cp bond_quartic.cpp ..
  cp bond_table.cpp ..
  cp dihedral_charmm.cpp ..
  cp dihedral_harmonic.cpp ..
  cp dihedral_helix.cpp ..
  cp dihedral_hybrid.cpp ..
  cp dihedral_multi_harmonic.cpp ..
  cp dihedral_opls.cpp ..
  cp improper_cvff.cpp ..
  cp improper_harmonic.cpp ..
  cp improper_hybrid.cpp ..
  cp improper_umbrella.cpp ..
  cp pair_hbond_dreiding_lj.cpp ..
  cp pair_hbond_dreiding_morse.cpp ..
  cp pair_lj_charmm_coul_charmm.cpp ..
  cp pair_lj_charmm_coul_charmm_implicit.cpp ..

  cp angle_charmm.h ..
  cp angle_cosine.h ..
  cp angle_cosine_delta.h ..
  cp angle_cosine_periodic.h ..
  cp angle_cosine_squared.h ..
  cp angle_harmonic.h ..
  cp angle_hybrid.h ..
  cp angle_table.h ..
  cp atom_vec_angle.h ..
  cp atom_vec_bond.h ..
  cp atom_vec_full.h ..
  cp atom_vec_molecular.h ..
  cp bond_fene.h ..
  cp bond_fene_expand.h ..
  cp bond_harmonic.h ..
  cp bond_morse.h ..
  cp bond_nonlinear.h ..
  cp bond_quartic.h ..
  cp bond_table.h ..
  cp dihedral_charmm.h ..
  cp dihedral_harmonic.h ..
  cp dihedral_helix.h ..
  cp dihedral_hybrid.h ..
  cp dihedral_multi_harmonic.h ..
  cp dihedral_opls.h ..
  cp improper_cvff.h ..
  cp improper_harmonic.h ..
  cp improper_hybrid.h ..
  cp improper_umbrella.h ..
  cp pair_hbond_dreiding_lj.h ..
  cp pair_hbond_dreiding_morse.h ..
  cp pair_lj_charmm_coul_charmm.h ..
  cp pair_lj_charmm_coul_charmm_implicit.h ..

elif (test $1 = 0) then

  rm -f ../angle_charmm.cpp
  rm -f ../angle_cosine.cpp
  rm -f ../angle_cosine_delta.cpp
  rm -f ../angle_cosine_periodic.cpp
  rm -f ../angle_cosine_squared.cpp
  rm -f ../angle_harmonic.cpp
  rm -f ../angle_hybrid.cpp
  rm -f ../angle_table.cpp
  rm -f ../atom_vec_angle.cpp
  rm -f ../atom_vec_bond.cpp
  rm -f ../atom_vec_full.cpp
  rm -f ../atom_vec_molecular.cpp
  rm -f ../bond_fene.cpp
  rm -f ../bond_fene_expand.cpp
  rm -f ../bond_harmonic.cpp
  rm -f ../bond_morse.cpp
  rm -f ../bond_nonlinear.cpp
  rm -f ../bond_quartic.cpp
  rm -f ../bond_table.cpp
  rm -f ../dihedral_charmm.cpp
  rm -f ../dihedral_harmonic.cpp
  rm -f ../dihedral_helix.cpp
  rm -f ../dihedral_hybrid.cpp
  rm -f ../dihedral_multi_harmonic.cpp
  rm -f ../dihedral_opls.cpp
  rm -f ../improper_cvff.cpp
  rm -f ../improper_harmonic.cpp
  rm -f ../improper_hybrid.cpp
  rm -f ../improper_umbrella.cpp
  rm -f ../pair_hbond_dreiding_lj.cpp
  rm -f ../pair_hbond_dreiding_morse.cpp
  rm -f ../pair_lj_charmm_coul_charmm.cpp
  rm -f ../pair_lj_charmm_coul_charmm_implicit.cpp

  rm -f ../angle_charmm.h
  rm -f ../angle_cosine.h
  rm -f ../angle_cosine_delta.h
  rm -f ../angle_cosine_periodic.h
  rm -f ../angle_cosine_squared.h
  rm -f ../angle_harmonic.h
  rm -f ../angle_hybrid.h
  rm -f ../angle_table.h
  rm -f ../atom_vec_angle.h
  rm -f ../atom_vec_bond.h
  rm -f ../atom_vec_full.h
  rm -f ../atom_vec_molecular.h
  rm -f ../bond_fene.h
  rm -f ../bond_fene_expand.h
  rm -f ../bond_harmonic.h
  rm -f ../bond_morse.h
  rm -f ../bond_nonlinear.h
  rm -f ../bond_quartic.h
  rm -f ../bond_table.h
  rm -f ../dihedral_charmm.h
  rm -f ../dihedral_harmonic.h
  rm -f ../dihedral_helix.h
  rm -f ../dihedral_hybrid.h
  rm -f ../dihedral_multi_harmonic.h
  rm -f ../dihedral_opls.h
  rm -f ../improper_cvff.h
  rm -f ../improper_harmonic.h
  rm -f ../improper_hybrid.h
  rm -f ../improper_umbrella.h
  rm -f ../pair_hbond_dreiding_lj.h
  rm -f ../pair_hbond_dreiding_morse.h
  rm -f ../pair_lj_charmm_coul_charmm.h
  rm -f ../pair_lj_charmm_coul_charmm_implicit.h

fi
