# Settings that the LAMMPS build will import when this package library is used
# See the README file for more explanation

python_SYSINC = $(shell which python2-config > /dev/null 2>&1 && python2-config --includes || python-config --includes )
python_SYSLIB = $(shell which python2-config > /dev/null 2>&1 && python2-config --ldflags || python-config --ldflags)
python_SYSPATH =
