// clang-format off
/* ----------------------------------------------------------------------
   LAMMPS - Large-scale Atomic/Molecular Massively Parallel Simulator
   https://www.lammps.org/, Sandia National Laboratories
   LAMMPS development team: developers@lammps.org

   Copyright (2003) Sandia Corporation.  Under the terms of Contract
   DE-AC04-94AL85000 with Sandia Corporation, the U.S. Government retains
   certain rights in this software.  This software is distributed under
   the GNU General Public License.

   See the README file in the top-level LAMMPS directory.
------------------------------------------------------------------------- */

/* ----------------------------------------------------------------------
   Contributing author: Mitch Murphy (alphataubio at gmail)
------------------------------------------------------------------------- */

#include "write_pdb.h"

#include "atom.h"
#include "atom_vec.h"
//#include "bond.h"
#include "comm.h"
#include "dihedral.h"
#include "domain.h"
#include "error.h"
#include "label_map.h"
#include "memory.h"
#include "output.h"
#include "version.h"

#include <cstring>
#include <string>

using namespace LAMMPS_NS;

static int compare_IDs(const int, const int, void *);

/* ----------------------------------------------------------------------
   Constructor
------------------------------------------------------------------------- */
WritePDB::WritePDB(LAMMPS *lmp) : Command(lmp) {}

/* ----------------------------------------------------------------------
   Command handler
------------------------------------------------------------------------- */
void WritePDB::command(int narg, char **arg) {
  if (narg < 1) error->all(FLERR, "Write_pdb command requires a filename");

  std::string filename = arg[0];
  write_pdb(filename);
}

/* ----------------------------------------------------------------------
   Function to write PDB file
------------------------------------------------------------------------- */
void WritePDB::write_pdb(const std::string &filename) {
  FILE *fp = fopen(filename.c_str(), "w");
  if (!fp) error->one(FLERR, "Cannot open PDB file for writing");

  const char *version = (const char *)LAMMPS_VERSION;
  utils::print(fp, "REMARK  GENERATED BY LAMMPS ({}{})\n", version, utils::date2num(version));
  utils::print(fp, "REMARK  with write_pdb command (https://docs.lammps.org/write_pdb.html)\n");
  utils::print(fp, "REMARK   ID NAME RES C MOL           X       Y       Z                      ELEMENT\n");

  int *tag = atom->tag;
  int *molecule = atom->molecule;
  double **x = atom->x;
  int *type = atom->type;
  std::string *segment = atom->segment;
  std::string *residue = atom->residue;
  std::string *name = atom->name;

  bigint nblocal = atom->nlocal;
  bigint natoms;
  MPI_Allreduce(&nblocal,&natoms,1,MPI_LMP_BIGINT,MPI_SUM,world);

  utils::logmesg(lmp, "*** natoms {}\n", natoms);

/* FIXME: collect all segment/residue/name from other procs
  int tmp,recvrow;

  if (comm->me == 0) {
    MPI_Status status;
    MPI_Request request;

    for (int iproc = 0; iproc < comm->nprocs; iproc++) {
      if (iproc) {
        MPI_Irecv(&buf[0][0],maxrow*ncol,MPI_CHAR,iproc,0,world,&request);
        MPI_Send(&tmp,0,MPI_INT,iproc,0,world);
        MPI_Wait(&request,&status);
        MPI_Get_count(&status,MPI_DOUBLE,&recvrow);
        recvrow /= ncol;
      } else recvrow = sendrow;

      atom->avec->write_data(fp,recvrow,buf);
    }

  } else {
    MPI_Recv(&tmp,0,MPI_INT,0,0,world,MPI_STATUS_IGNORE);
    MPI_Rsend(&buf[0][0],sendrow*ncol,MPI_DOUBLE,0,0,world);
  }
*/

  int *order;
  tagint *ids;

  memory->create(order, natoms, "write_pdb:order");
  memory->create(ids, natoms, "write_pdb:ids");

  for (int i = 0; i < natoms; i++) {
    ids[i] = tag[i];
    order[i] = i;
  }

  utils::merge_sort(order, natoms, (void *)ids, compare_IDs);

  for (int i = 0; i < natoms; i++) {

    int j = order[i];

    if( tag[j]>99999 ) error->one(FLERR, "PDB format only supports atom serial (tag in LAMMPS) up to 99999.");

    if( molecule[j]>9999 ) error->one(FLERR, "PDB format only supports residue seq (molecule in LAMMPS) up to 9999.");

    // FIXME: handle *segment / *residue / *name = nullptr

    std::string atom_name = name[j];
    std::string element;

    if( atom_name=="POT" ) element="K";
    else if ( atom_name=="SOD" ) element="Na";
    else if ( atom_name=="CAL" ) element="Ca";
    else if ( atom_name=="MG" ) element="Mg";
    else if ( atom_name=="CLA" ) element="Cl";
    else element=atom_name.substr(0,1);

    utils::print(fp, "ATOM  {:5d} {:4.4s} {:3.3s} {:1.1s}{:4d}    {:8.3f}{:8.3f}{:8.3f}                      {:3.3s}\n",
            tag[j], atom_name, residue[j], segment[j], molecule[j], x[j][0], x[j][1], x[j][2], element);
  }

  utils::print(fp, "END\n");
  fclose(fp);
}

/* ----------------------------------------------------------------------
   comparison function invoked by merge_sort()
   void pointer contains list of atom IDs
------------------------------------------------------------------------- */

int compare_IDs(const int i, const int j, void *ptr)
{
  tagint *ids = (tagint *) ptr;
  if (ids[i] < ids[j]) return -1;
  if (ids[i] > ids[j]) return 1;
  return 0;
}
