
# Create the coordinates of the atoms using PACKMOL
cd packmol_files

  packmol < input.packmol
  mv -f system.xyz ../moltemplate_files/

cd ..

# Create LAMMPS input files this way:
cd moltemplate_files

  # run moltemplate
  moltemplate.sh -atomstyle "hybrid sphere dipole molecular" \
                 -xyz system.xyz system.lt


  # This will generate various files with names ending in *.in* and *.data.
  # Move them to the directory where you plan to run LAMMPS (in this case "../")
  mv -f system.data system.in* ../

  # Optional:
  # The "./output_ttree/" directory is full of temporary files generated by
  # moltemplate.  They can be useful for debugging, but are usually thrown away.
  rm -rf output_ttree/ system.xyz

cd ../

