#include <cuda/TestCuda_SubView_c01.cpp>
#include <cuda/TestCuda_SubView_c02.cpp>
#include <cuda/TestCuda_SubView_c03.cpp>
#include <cuda/TestCuda_SubView_c04.cpp>
#include <cuda/TestCuda_SubView_c05.cpp>
#include <cuda/TestCuda_SubView_c06.cpp>
#include <cuda/TestCuda_SubView_c07.cpp>
#include <cuda/TestCuda_SubView_c08.cpp>
#include <cuda/TestCuda_SubView_c09.cpp>
#include <cuda/TestCuda_SubView_c10.cpp>
#include <cuda/TestCuda_SubView_c11.cpp>
#include <cuda/TestCuda_SubView_c12.cpp>
#include <cuda/TestCuda_SubView_c13.cpp>
