function(kokkos_set_msvc_flags full_standard int_standard)
  if(CMAKE_CXX_EXTENSIONS)
    set(KOKKOS_CXX_STANDARD_FLAG "" PARENT_SCOPE)
    set(KOKKOS_CXX_INTERMEDIATE_STANDARD_FLAG "" PARENT_SCOPE)
  else()
    set(KOKKOS_CXX_STANDARD_FLAG "" PARENT_SCOPE)
    set(KOKKOS_CXX_INTERMEDIATE_STANDARD_FLAG "" PARENT_SCOPE)
  endif()
endfunction()
