
FUNCTION(kokkos_set_msvc_flags full_standard int_standard)
  IF (CMAKE_CXX_EXTENSIONS)
    SET(KOKKOS_CXX_STANDARD_FLAG "" PARENT_SCOPE)
    SET(KOKKOS_CXX_INTERMEDIATE_STANDARD_FLAG "" PARENT_SCOPE)
  ELSE()
    SET(KOKKOS_CXX_STANDARD_FLAG "" PARENT_SCOPE)
    SET(KOKKOS_CXX_INTERMEDIATE_STANDARD_FLAG "" PARENT_SCOPE)
  ENDIF()
ENDFUNCTION()

