
IF (KOKKOS_CXX_COMPILER_ID STREQUAL Clang)
   KOKKOS_FIND_IMPORTED(CUDA INTERFACE
    LIBRARIES cudart cuda
    LIBRARY_PATHS ENV LD_LIBRARY_PATH ENV CUDA_PATH
    ALLOW_SYSTEM_PATH_FALLBACK
   )
ELSE()
   KOKKOS_CREATE_IMPORTED_TPL(CUDA INTERFACE
    LINK_LIBRARIES cuda
   )
ENDIF()

