# Install/unInstall package files in LAMMPS

if (test $1 = 1) then

  cp ewald.cpp ..
  cp ewald_disp.cpp ..
  cp msm.cpp ..
  cp pppm.cpp ..
  cp pppm_old.cpp ..
  cp pppm_cg.cpp ..
  cp pppm_disp.cpp ..
  cp pppm_disp_tip4p.cpp ..
  cp pppm_tip4p.cpp ..
  cp pair_born_coul_long.cpp ..
  cp pair_born_coul_msm.cpp ..
  cp pair_buck_coul_long.cpp ..
  cp pair_buck_coul_msm.cpp ..
  cp pair_buck_disp_coul_long.cpp ..
  cp pair_coul_long.cpp ..
  cp pair_coul_msm.cpp ..
  cp pair_lj_charmm_coul_long.cpp ..
  cp pair_lj_charmm_coul_msm.cpp ..
  cp pair_lj_cut_coul_long.cpp ..
  cp pair_lj_cut_coul_long_tip4p.cpp ..
  cp pair_lj_cut_coul_msm.cpp ..
  cp pair_lj_disp_coul_long.cpp ..
  cp pair_lj_disp_coul_long_tip4p.cpp ..
  cp fft3d.cpp ..
  cp fft3d_wrap.cpp ..
  cp remap.cpp ..
  cp remap_wrap.cpp ..

  cp ewald.h ..
  cp ewald_disp.h ..
  cp msm.h ..
  cp pppm.h ..
  cp pppm_old.h ..
  cp pppm_cg.h ..
  cp pppm_disp.h ..
  cp pppm_disp_tip4p.h ..
  cp pppm_tip4p.h ..
  cp pair_born_coul_long.h ..
  cp pair_born_coul_msm.h ..
  cp pair_buck_coul_long.h ..
  cp pair_buck_coul_msm.h ..
  cp pair_buck_disp_coul_long.h ..
  cp pair_coul_long.h ..
  cp pair_coul_msm.h ..
  cp pair_lj_charmm_coul_long.h ..
  cp pair_lj_charmm_coul_msm.h ..
  cp pair_lj_cut_coul_long.h ..
  cp pair_lj_cut_coul_long_tip4p.h ..
  cp pair_lj_cut_coul_msm.h ..
  cp pair_lj_disp_coul_long.h ..
  cp pair_lj_disp_coul_long_tip4p.h ..
  cp fft3d.h ..
  cp fft3d_wrap.h ..
  cp remap.h ..
  cp remap_wrap.h ..
  cp kissfft.h ..
  cp math_complex.h ..
  cp math_vector.h ..

elif (test $1 = 0) then

  rm -f ../ewald.cpp
  rm -f ../ewald_disp.cpp
  rm -f ../msm.cpp
  rm -f ../pppm.cpp
  rm -f ../pppm_old.cpp
  rm -f ../pppm_cg.cpp
  rm -f ../pppm_disp.cpp
  rm -f ../pppm_disp_tip4p.cpp
  rm -f ../pppm_tip4p.cpp
  rm -f ../pair_born_coul_long.cpp
  rm -f ../pair_born_coul_msm.cpp
  rm -f ../pair_buck_coul_long.cpp
  rm -f ../pair_buck_coul_msm.cpp
  rm -f ../pair_buck_disp_coul_long.cpp
  rm -f ../pair_coul_long.cpp
  rm -f ../pair_coul_msm.cpp
  rm -f ../pair_lj_charmm_coul_long.cpp
  rm -f ../pair_lj_charmm_coul_msm.cpp
  rm -f ../pair_lj_cut_coul_long.cpp
  rm -f ../pair_lj_cut_coul_long_tip4p.cpp
  rm -f ../pair_lj_cut_coul_msm.cpp
  rm -f ../pair_lj_disp_coul_long.cpp
  rm -f ../pair_lj_disp_coul_long_tip4p.cpp
  rm -f ../fft3d.cpp
  rm -f ../fft3d_wrap.cpp
  rm -f ../remap.cpp
  rm -f ../remap_wrap.cpp

  rm -f ../ewald.h
  rm -f ../ewald_disp.h
  rm -f ../msm.h
  rm -f ../pppm.h
  rm -f ../pppm_old.h
  rm -f ../pppm_cg.h
  rm -f ../pppm_disp.h
  rm -f ../pppm_disp_tip4p.h
  rm -f ../pppm_tip4p.h
  rm -f ../pair_born_coul_long.h
  rm -f ../pair_born_coul_msm.h
  rm -f ../pair_buck_coul_long.h
  rm -f ../pair_buck_coul_msm.h
  rm -f ../pair_buck_disp_coul_long.h
  rm -f ../pair_coul_long.h
  rm -f ../pair_coul_msm.h
  rm -f ../pair_lj_charmm_coul_long.h
  rm -f ../pair_lj_charmm_coul_msm.h
  rm -f ../pair_lj_cut_coul_long.h
  rm -f ../pair_lj_cut_coul_long_tip4p.h
  rm -f ../pair_lj_cut_coul_msm.h
  rm -f ../pair_lj_disp_coul_long.h
  rm -f ../pair_lj_disp_coul_long_tip4p.h
  rm -f ../fft3d.h
  rm -f ../fft3d_wrap.h
  rm -f ../remap.h
  rm -f ../remap_wrap.h
  rm -f ../kissfft.h
  rm -f ../math_vector.h
  rm -f ../math_complex.h

fi
