blank_issues_enabled: true
contact_links:
  - name: Report a security vulnerability
    url: https://github.com/lammps/lammps/security/policy
    about: Please do not report security problems in a public issue. The security policy explains how to report them privately.
