
# Run moltemplate this way:

moltemplate.sh -pdb solvate.pdb system.lt


# The PDB file was generated by the "solvate" utility which comes with VMD.
# (To generate this file yourself, run VMD, click on the "Extensions" menu,
# and select Modeling-->Add Solvation Box.
# In this example, I made a box whose x,y,z dimensions were 16,24,24.)

