CUDA_HOME = $(HOME)/cuda
NVCC  = $(CUDA_HOME)/bin/nvcc 

CUDA_ARCH = -arch=sm_13
CUDA_PRECISION = -D_SINGLE_DOUBLE
CUDA_INCLUDE = -I$(CUDA_HOME)/include 
CUDA_LIB = -L$(CUDA_HOME)/lib64 -Xlinker -rpath -Xlinker $(CUDA_HOME)/lib64
CUDA_OPTS = -DUNIX -O3 -Xptxas -v --use_fast_math 

CUDR_CPP = mpic++ -DMPI_GERYON -DUCL_NO_EXIT -I$(CUDA_HOME)/include 
CUDR_OPTS = -O3 -ffast-math -funroll-loops -DMPI_GERYON

BIN_DIR = ./
OBJ_DIR = ./
LIB_DIR = ./
AR = ar
BSH = /bin/sh

include Nvidia.makefile

