# /* ----------------------------------------------------------------------
#  Generic Linux Makefile for OpenCL
# ------------------------------------------------------------------------- */

# which file will be copied to Makefile.lammps

EXTRAMAKE = Makefile.lammps.opencl

# OCL_TUNE = -DFERMI_OCL       # -- Uncomment for NVIDIA Fermi
# OCL_TUNE = -DKEPLER_OCL    # -- Uncomment for NVIDIA Kepler
# OCL_TUNE = -DCYPRESS_OCL   # -- Uncomment for AMD Cypress
OCL_TUNE = -DGENERIC_OCL   # -- Uncomment for generic device

# this setting should match LAMMPS Makefile
# one of LAMMPS_SMALLBIG (default), LAMMPS_BIGBIG and LAMMPS_SMALLSMALL

LMP_INC = -DLAMMPS_SMALLBIG

OCL_INC = -I/opt/intel/oneapi/compiler/latest/linux/include/sycl/ # Path to CL directory
OCL_CPP = mpicxx -cxx=icpx -DCUDA_PROXY $(DEFAULT_DEVICE) -xHost -O2 -ffp-model=fast -qoverride-limits -DMPI_GERYON -DGERYON_NUMA_FISSION -DUCL_NO_EXIT -DMPICH_IGNORE_CXX_SEEK $(LMP_INC) $(OCL_INC) -DGERYON_NO_PROF
OCL_LINK = -L/opt/intel/oneapi/compiler/latest/linux/lib/ -lOpenCL
OCL_PREC = -D_SINGLE_DOUBLE

BIN_DIR = ./
OBJ_DIR = ./
LIB_DIR = ./
AR = ar
BSH = /bin/sh

include Opencl.makefile

