OCL_CPP = mpic++ -O3 -DMPI_GERYON -DMPICH_IGNORE_CXX_SEEK -I/usr/local/cuda/include/
OCL_LINK = -lOpenCL
OCL_PREC = -D_SINGLE_SINGLE

BIN_DIR =  /home/wb8/bin
OBJ_DIR = /home/wb8/obj/lammps
LIB_DIR = /home/wb8/obj/lammps
AR = ar
BSH = /bin/sh

include Opencl.makefile

