# Settings that the LAMMPS build will import when this package library is used
# settings for CUDA BUILDS
#gpu_SYSINC =
#gpu_SYSLIB = -lcudart -lcuda
#gpu_SYSPATH = -L$(HOME)/cuda/lib64 -Wl,-rpath,$(HOME)/cuda/lib64

# Settings for OpenCL BUILDS
gpu_SYSINC =
gpu_SYSLIB = -lOpenCL
gpu_SYSPATH = -L$(HOME)/cuda/lib64 -Wl,-rpath,$(HOME)/cuda/lib64


