# Settings that the LAMMPS build will import when this package library is used
CUDA_FLAGS := -I/home/crtrott/lib/cuda/include -DUNIX  -DFFT_CUFFT -DCUDA_PRECISION=2 -DCUDA_ARCH=20 
CUDA_USRLIB_CONDITIONAL := -L/home/crtrott/lib/cuda/lib -L/home/crtrott/lib/cuda/lib64 -lcufft
 
 user-cuda_SYSINC = ${CUDA_FLAGS}
 user-cuda_SYSLIB = -lcuda -lcudart -lrt
 user-cuda_SYSPATH = $(CUDA_USRLIB_CONDITIONAL)

