# Settings that the LAMMPS build will import when this package library is used
CUDA_FLAGS := -I/usr/local/cuda-5.0/include -DUNIX  -DFFT_CUFFT -DCUDA_PRECISION=1 -DX_PRECISION=2 -DV_PRECISION=2 -DCUDA_ARCH=20 
CUDA_USRLIB_CONDITIONAL := -L/usr/local/cuda-5.0/lib -L/usr/local/cuda-5.0/lib64 -lcufft
 
user-cuda_SYSINC = ${CUDA_FLAGS}
user-cuda_SYSLIB = -lcuda -lcudart 
user-cuda_SYSPATH = $(CUDA_USRLIB_CONDITIONAL)

