
#precision setting: 1 single, 2 double, 4 mixed
precision ?= 1

#GPU architecture (compute capability): 13, 20, 21
arch ?= 21

#Using cufft (should not be changed)
cufft ?= 1

#Using dbg mode 
dbg ?= 0

#On mac machines set this to 0 in order to avoid usage of linux specific precision timer
prec_timer ?= 1

