# Settings that the LAMMPS build will import when this package library is used

CUDA_INSATLL_PATH = /usr/local/cuda-3.2
CUDA_USRLIB_CONDITIONAL =

user-cuda_SYSINC = -I$(CUDA_INSTALL_PATH)/include 
user-cuda_SYSLIB = -lcuda -lcudart -lrt 
user-cuda_SYSPATH = -L$(CUDA_INSTALL_PATH)/lib64 -L$(CUDA_INSTALL_PATH)/lib $(CUDA_USRLIB_CONDITIONAL)
