SHELL = /bin/sh

# which file will be copied to Makefile.lammps

EXTRAMAKE = Makefile.lammps.empty

# ------ MAKE PROCEDURE ------

lib: 	$(OBJ)
	mkdir -p build
	cd build; cmake -Dlibtype=STATIC  -Dlanguage=C -D CMAKE_POSITION_INDEPENDENT_CODE=yes -D CMAKE_C_COMPILER=mpicc -D CMAKE_CXX_COMPILER=mpicxx ../MDI_Library; make
	@cp $(EXTRAMAKE) Makefile.lammps

# ------ CLEAN ------

clean:
	-rm *.o *.h $(LIB)
	-rm -r build
