SHELL = /bin/sh

# which file will be copied to Makefile.lammps

EXTRAMAKE = Makefile.lammps.empty

# ------ MAKE PROCEDURE ------

lib: 	$(OBJ)
	mkdir -p build
	cd build && cmake -D libtype=STATIC -D language=C -D CMAKE_POSITION_INDEPENDENT_CODE=yes -D mpi=ON -D plugins=ON -D python_plugins=ON -D CMAKE_C_COMPILER=gcc ../MDI_Library && make
	@cp $(EXTRAMAKE) Makefile.lammps

# ------ CLEAN ------

clean:
	-rm *.o *.h $(LIB)
	-rm -r build
