SHELL = /bin/sh

# which file will be copied to Makefile.lammps

EXTRAMAKE = Makefile.lammps.empty

# ------ MAKE PROCEDURE ------

lib: 	$(OBJ)
	mkdir -p build
	cd build; cmake -Dlibtype=SHARED -Dlanguage=CXX -D CMAKE_C_COMPILER=gcc -D CMAKE_CXX_COMPILER=g++ ../MDI_Library; make
	@cp $(EXTRAMAKE) Makefile.lammps

# ------ CLEAN ------

clean:
	-rm *.o *.h $(LIB)
	-rm -r build
