# Settings that the LAMMPS build will import when this package library is used

# settings for VTK-5.8.0 on RHEL/CentOS 6.x
 vtk_SYSINC = -I/usr/include/vtk
 vtk_SYSLIB = -lvtkCommon -lvtkIO 
 vtk_SYSPATH = -L/usr/lib64/vtk

# settings for VTK 6.2.0 on Fedora 23
#vtk_SYSINC = -I/usr/include/vtk
#vtk_SYSLIB = -lvtkCommonCore -lvtkIOCore -lvtkCommonDataModel -lvtkIOXML -lvtkIOLegacy -lvtkIOParallelXML
#vtk_SYSPATH = -L/usr/lib64/vtk

