#info all out log
units  metal
atom_style  atomic
boundary    p p p
atom_modify    map hash
read_data  latte_cell_0.data
mass  1 1.00
mass  2 14.00
mass  3 15.999

pair_style     zero 5.7
pair_coeff     * *


compute   	ace all mliap descriptor ace coupling_coefficients.yace model linear gradgradflag 1

thermo 1
thermo_style  custom step c_ace[1][1]
thermo_modify   norm no

fix             pc all ave/time 1 1 1 c_ace[*] file desc_out.dat  mode vector


run 0

