# preset that turns on all existing packages off. can be used to reset
# an existing package selection without losing any other settings

set(ALL_PACKAGES ASPHERE BODY CLASS2 COLLOID COMPRESS CORESHELL DIPOLE GPU
  GRANULAR KIM KOKKOS KSPACE LATTE MANYBODY MC MESSAGE MISC ML-IAP MOLECULE
  MPIIO MSCG OPT PERI PLUGIN POEMS PYTHON QEQ REPLICA RIGID SHOCK ML-SNAP SPIN
  SRD VORONOI
  ADIOS ATC AWPMD BROWNIAN BOCS CG-DNA CG-SDK
  COLVARS DIFFRACTION DPD-REACT DRUDE EFF FEP H5MD
  ML-HDNNP INTEL LATBOLTZ MANIFOLD MDI MEAM DPD-MESO
  MESONT MGPT USER-MISC MOFFF MOLFILE NETCDF OPENMP
  ML-PACE PHONON PLUMED PTM QMMM QTB ML-QUIP ML-RANN
  REACTION REAXFF SCAFACOS DPD-SMOOTH MACHDYN SMTBQ SPH
  TALLY UEF VTK YAFF DIELECTRIC)

foreach(PKG ${ALL_PACKAGES})
  set(PKG_${PKG} OFF CACHE BOOL "" FORCE)
endforeach()
