# preset that turns on all existing packages. using the combination
# this preset followed by the nolib.cmake preset should configure a
# LAMMPS binary, with as many packages included, that can be compiled
# with just a working C++ compiler and an MPI library.

set(ALL_PACKAGES ASPHERE BODY CLASS2 COLLOID COMPRESS CORESHELL DIPOLE GPU
  GRANULAR KIM KOKKOS KSPACE LATTE MANYBODY MC MESSAGE MISC ML-IAP MOLECULE
  MPIIO MSCG OPT PERI PLUGIN POEMS PYTHON QEQ REPLICA RIGID SHOCK ML-SNAP SPIN
  SRD VORONOI
  ADIOS ATC AWPMD BROWNIAN BOCS CG-DNA CG-SDK
  COLVARS DIFFRACTION DPD-REACT DRUDE EFF FEP H5MD
  ML-HDNNP INTEL LATBOLTZ MANIFOLD MDI MEAM DPD-MESO
  MESONT MGPT USER-MISC MOFFF MOLFILE NETCDF OPENMP
  ML-PACE PHONON PLUMED PTM QMMM QTB ML-QUIP ML-RANN
  REACTION REAXFF SCAFACOS DPD-SMOOTH MACHDYN SMTBQ SPH
  TALLY UEF VTK YAFF DIELECTRIC)

foreach(PKG ${ALL_PACKAGES})
  set(PKG_${PKG} ON CACHE BOOL "" FORCE)
endforeach()
