# preset that turns on all existing packages. using the combination
# this preset with the nolib.cmake preset should configure a LAMMPS
# binary, that can be compiled with just a working C++ compiler.

set(ALL_PACKAGES ASPHERE BODY CLASS2 COLLOID COMPRESS CORESHELL DIPOLE GPU
        GRANULAR KIM KOKKOS KSPACE LATTE MANYBODY MC MISC MOLECULE MPIIO
        MSCG OPT PERI POEMS PYTHON QEQ REPLICA RIGID SHOCK SNAP SPIN SRD
        VORONOI
        USER-ADIOS USER-ATC USER-AWPMD USER-BOCS USER-CGDNA USER-CGSDK
        USER-COLVARS USER-DIFFRACTION USER-DPD USER-DRUDE USER-EFF USER-FEP
        USER-H5MD USER-INTEL USER-LB USER-MANIFOLD USER-MEAMC USER-MESO
        USER-MGPT USER-MISC USER-MOFFF USER-MOLFILE USER-NETCDF USER-OMP
        USER-PHONON USER-PLUMED USER-PTM USER-QMMM USER-QTB USER-QUIP
        USER-REAXC USER-SCAFACOS USER-SDPD USER-SMD USER-SMTBQ USER-SPH
        USER-TALLY USER-UEF USER-VTK USER-YAFF)

foreach(PKG ${ALL_PACKAGES})
  set(PKG_${PKG} ON CACHE BOOL "" FORCE)
endforeach()
