if(NOT ZLIB_FOUND)
  find_package(ZLIB REQUIRED)
endif()
target_link_libraries(lammps PRIVATE ZLIB::ZLIB)

find_package(PkgConfig QUIET)
if(PkgConfig_FOUND)
  pkg_check_modules(Zstd IMPORTED_TARGET libzstd>=1.4)
  if(Zstd_FOUND)
    target_compile_definitions(lammps PRIVATE -DLAMMPS_ZSTD)
    target_link_libraries(lammps PRIVATE PkgConfig::Zstd)
  endif()
endif()