if(PKG_USER-QMMM)
  enable_language(C)

  if(NOT BUILD_LIB)
    message(FATAL_ERROR "Building a QM/MM executable with USER-QMMM requires BUILD_LIB=yes")
  endif()
  if(NOT BUILD_SHARED_LIBS)
    message(WARNING "It is recommended to use BUILD_SHARED_LIBS=yes with USER-QMMM")
  endif()
  add_library(qmmm STATIC ${LAMMPS_LIB_SOURCE_DIR}/qmmm/libqmmm.c)
  target_link_libraries(lammps PRIVATE qmmm)
  target_include_directories(qmmm PUBLIC ${LAMMPS_LIB_SOURCE_DIR}/qmmm)
endif()
