# Settings for libraries used by specific LAMMPS packages
# this file is auto-edited when those packages are included/excluded

PKGINC =   -I../../lib/poems -I../../lib/meam -I../../lib/reax 
PKGPATH =  -L../../lib/poems -L../../lib/meam -L../../lib/reax 
PKGLIB =   -lpoems -lmeam -lreax 
