# Make.sh = update style_*.h and packages_*.h files
# Syntax: sh Make.sh style
#         sh Make.sh packages

# turn off enforced customizations
GREP_OPTIONS=
# enforce using portable C locale
LC_ALL=C
export LC_ALL GREP_OPTIONS

# function to create one style_*.h file

style () {
  list=`grep -sl $1 $2*.h`
  if (test -e style_$3.tmp) then
    rm -f style_$3.tmp
  fi
  for file in $list; do
    qfile="\"$file\""
    echo "#include $qfile" >> style_$3.tmp
  done
  if (test ! -e style_$3.tmp) then
    if (test ! -e style_$3.h) then
      touch style_$3.h
    elif (test "`cat style_$3.h`" != "") then
      rm -f style_$3.h
      touch style_$3.h
    fi
  elif (test ! -e style_$3.h) then
    mv style_$3.tmp style_$3.h
  elif (test "`diff --brief style_$3.h style_$3.tmp`" != "") then
    mv style_$3.tmp style_$3.h
  else
    rm -f style_$3.tmp
  fi
}

# function to create one packages_*.h file

packages () {
  list=`grep -sl $1 */$2*.h`
  if (test -e packages_$3.tmp) then
    rm -f packages_$3.tmp
  fi
  for file in $list; do
    dir="\"`dirname $file`\""
    echo "#undef PACKAGE" >> packages_$3.tmp
    echo "#define PACKAGE $dir" >> packages_$3.tmp
    qfile="\"$file\""
    echo "#include $qfile" >> packages_$3.tmp
  done
  if (test ! -e packages_$3.tmp) then
    if (test ! -e packages_$3.h) then
      touch packages_$3.h
    elif (test "`cat packages_$3.h`" != "") then
      rm -f packages_$3.h
      touch packages_$3.h
    fi
  elif (test ! -e packages_$3.h) then
    mv packages_$3.tmp packages_$3.h
  elif (test "`diff --brief packages_$3.h packages_$3.tmp`" != "") then
    mv packages_$3.tmp packages_$3.h
  else
    rm -f packages_$3.tmp
  fi
}

# function to create one style_*.cpp registration translation unit
# args: 1=CLASS macro 2=file prefix 3=style name 4=XxxStyle macro 5=base class
#       6=registry accessor 7=register function 8=one-arg creator (1/0)
#       9=extra include headers (space separated)
# parses the XxxStyle(key,Class) markers into explicit add_builtin() calls and
# copies preprocessor directives inside the marker block through verbatim so
# build-config-dependent markers stay guarded.

stylesource () {
  list=`grep -sl "$1" $2*.h | LC_ALL=C sort`
  rm -f style_$3.cpp.tmp
  {
    echo "// auto-generated by the LAMMPS build system from style markers. DO NOT EDIT."
    echo ""
    echo "#include \"lammps.h\""
    echo "#include \"creator_registry.h\""
    for inc in $9; do echo "#include \"$inc\""; done
    echo ""
    awk -v macro="$4" -v base="$5" -v accessor="$6" -v regfunc="$7" -v onearg="$8" '
      FNR==1 { state=0; depth=0; inc=inc "#include \"" FILENAME "\"\n" }
      {
        line=$0
        if (state==0) {
          if (line ~ /^#ifdef[ \t]+[A-Z_]+_CLASS/) { state=1; depth=1 }
          next
        }
        if (state==2) next
        if (line ~ /^[ \t]*#[ \t]*if/)    { depth++; d=line; sub(/^[ \t]*/,"",d); ent=ent d "\n"; next }
        if (line ~ /^[ \t]*#[ \t]*elif/)  { if (depth>1) { d=line; sub(/^[ \t]*/,"",d); ent=ent d "\n" } next }
        if (line ~ /^[ \t]*#[ \t]*else/)  { if (depth==1) state=2; else { d=line; sub(/^[ \t]*/,"",d); ent=ent d "\n" } next }
        if (line ~ /^[ \t]*#[ \t]*endif/) { depth--; if (depth==0) state=2; else { d=line; sub(/^[ \t]*/,"",d); ent=ent d "\n" } next }
        if (line ~ ("^[ \t]*" macro "\\(")) {
          lp=index(line,"("); rest=substr(line,lp+1)
          cp=index(rest,")"); inner=substr(rest,1,cp-1)
          ci=index(inner,","); key=substr(inner,1,ci-1); cls=substr(inner,ci+1)
          gsub(/^[ \t]+|[ \t]+$/,"",key); gsub(/^[ \t]+|[ \t]+$/,"",cls)
          ent=ent "  " accessor "().add_builtin(\"" key "\", &creator<" cls ">);\n"
        }
      }
      END {
        printf "%s", inc
        print ""
        print "namespace LAMMPS_NS {"
        print ""
        if (onearg=="1") {
          print "template <typename T> static " base " *creator(LAMMPS *lmp)"
          print "{"; print "  return new T(lmp);"; print "}"
        } else {
          print "template <typename T> static " base " *creator(LAMMPS *lmp, int narg, char **arg)"
          print "{"; print "  return new T(lmp, narg, arg);"; print "}"
        }
        print ""
        print "void " regfunc "()"
        print "{"
        printf "%s", ent
        print "}"
        print ""
        print "}    // namespace LAMMPS_NS"
      }
    ' $list
  } > style_$3.cpp.tmp

  if (test ! -e style_$3.cpp) then
    mv style_$3.cpp.tmp style_$3.cpp
  elif (test "`diff --brief style_$3.cpp style_$3.cpp.tmp`" != "") then
    mv style_$3.cpp.tmp style_$3.cpp
  else
    rm -f style_$3.cpp.tmp
  fi
}

# emit package_styles() entries for one category (all packages, enabled or not)
# args: 1=XxxStyle macro 2=file prefix 3=struct member

pkgentries () {
  list=`grep -sl "$1(" */$2*.h | LC_ALL=C sort`
  for file in $list; do
    pkg=`dirname $file`
    awk -v macro="$1" -v member="$3" -v pkg="$pkg" '
      $0 ~ (macro "\\(") {
        lp=index($0,"("); rest=substr($0,lp+1); cp=index(rest,")"); inner=substr(rest,1,cp-1)
        ci=index(inner,","); key=substr(inner,1,ci-1)
        gsub(/^[ \t]+|[ \t]+$/,"",key)
        print "  package_styles()." member "[\"" key "\"] = \"" pkg "\";"
      }
    ' $file
  done
}

# create the single package_registry.cpp (style keyword -> package name)

packageregistry () {
  rm -f package_registry.cpp.tmp
  {
    echo "// auto-generated by the LAMMPS build system from style markers. DO NOT EDIT."
    echo ""
    echo "#include \"package_registry.h\""
    echo ""
    echo "namespace LAMMPS_NS {"
    echo ""
    echo "void register_package_styles()"
    echo "{"
    pkgentries AngleStyle     angle_     angle_styles
    pkgentries AtomStyle      atom_vec_  atom_styles
    pkgentries BodyStyle      body_      body_styles
    pkgentries BondStyle      bond_      bond_styles
    pkgentries CommandStyle   ""         command_styles
    pkgentries ComputeStyle   compute_   compute_styles
    pkgentries DihedralStyle  dihedral_  dihedral_styles
    pkgentries DumpStyle      dump_      dump_styles
    pkgentries FixStyle       fix_       fix_styles
    pkgentries ImproperStyle  improper_  improper_styles
    pkgentries IntegrateStyle ""         integrate_styles
    pkgentries KSpaceStyle    ""         kspace_styles
    pkgentries MinimizeStyle  min_       minimize_styles
    pkgentries PairStyle      pair_      pair_styles
    pkgentries ReaderStyle    reader_    reader_styles
    pkgentries RegionStyle    region_    region_styles
    echo "}"
    echo ""
    echo "}    // namespace LAMMPS_NS"
  } > package_registry.cpp.tmp

  if (test ! -e package_registry.cpp) then
    mv package_registry.cpp.tmp package_registry.cpp
  elif (test "`diff --brief package_registry.cpp package_registry.cpp.tmp`" != "") then
    mv package_registry.cpp.tmp package_registry.cpp
  else
    rm -f package_registry.cpp.tmp
  fi
}

# create individual style files
# called by "make machine"
# col 1 = string to search for
# col 2 = search in *.h files starting with this name
# col 3 = name of style file
# col 4 = file that includes the style file
# col 5 = optional 2nd file that includes the style file

cmd=$1

if (test $cmd = "style") || (test $cmd = "packages") then

  $cmd ANGLE_CLASS        angle_         angle         force
  $cmd ATOM_CLASS         atom_vec_      atom          atom      atom_vec_hybrid
  $cmd BODY_CLASS         body_          body          atom_vec_body
  $cmd BOND_CLASS         bond_          bond          force
  $cmd COMMAND_CLASS      ""             command       input
  $cmd COMPUTE_CLASS      compute_       compute       modify
  $cmd DIHEDRAL_CLASS     dihedral_      dihedral      force
  $cmd DUMP_CLASS         dump_          dump          output    write_dump
  $cmd FIX_CLASS          fix_           fix           modify
  $cmd GRAN_SUB_MOD_CLASS gran_sub_mod_  gran_sub_mod  granular_model
  $cmd IMPROPER_CLASS     improper_      improper      force
  $cmd INTEGRATE_CLASS    ""             integrate     update
  $cmd KSPACE_CLASS       ""             kspace        force
  $cmd MINIMIZE_CLASS     min_           minimize      update
  $cmd NBIN_CLASS         nbin_          nbin          neighbor
  $cmd NPAIR_CLASS        npair_         npair         neighbor
  $cmd NSTENCIL_CLASS     nstencil_      nstencil      neighbor
  $cmd NTOPO_CLASS        ntopo_         ntopo         neighbor
  $cmd PAIR_CLASS         pair_          pair          force
  $cmd READER_CLASS       reader_        reader        read_dump
  $cmd REGION_CLASS       region_        region        domain

fi

# generate style_*.cpp registration translation units for migrated categories
# args: CLASS prefix style XxxStyle base accessor regfunc one-arg "includes"

if (test $cmd = "style") then

  stylesource PAIR_CLASS     pair_     pair     PairStyle     Pair     Force::pair_styles     register_pair_styles     1 "force.h pair.h"
  stylesource BOND_CLASS     bond_     bond     BondStyle     Bond     Force::bond_styles     register_bond_styles     1 "force.h bond.h"
  stylesource ANGLE_CLASS    angle_    angle    AngleStyle    Angle    Force::angle_styles    register_angle_styles    1 "force.h angle.h"
  stylesource DIHEDRAL_CLASS dihedral_ dihedral DihedralStyle Dihedral Force::dihedral_styles register_dihedral_styles 1 "force.h dihedral.h"
  stylesource IMPROPER_CLASS improper_ improper ImproperStyle Improper Force::improper_styles register_improper_styles 1 "force.h improper.h"
  stylesource KSPACE_CLASS   ""        kspace   KSpaceStyle   KSpace   Force::kspace_styles   register_kspace_styles   1 "force.h kspace.h"
  stylesource FIX_CLASS       fix_      fix       FixStyle       Fix       Modify::fix_styles       register_fix_styles       0 "modify.h fix.h"
  stylesource COMPUTE_CLASS   compute_  compute   ComputeStyle   Compute   Modify::compute_styles   register_compute_styles   0 "modify.h compute.h"
  stylesource INTEGRATE_CLASS ""        integrate IntegrateStyle Integrate Update::integrate_styles register_integrate_styles 0 "update.h integrate.h"
  stylesource MINIMIZE_CLASS  min_      minimize  MinimizeStyle  Min       Update::minimize_styles  register_minimize_styles  1 "update.h min.h"
  stylesource REGION_CLASS    region_   region    RegionStyle    Region    Domain::region_styles    register_region_styles    0 "domain.h region.h"

  packageregistry

fi
