# Make.sh = update generated style_*.h and style_*.cpp and package_registry.cpp
# Syntax: sh Make.sh style

# turn off enforced customizations
GREP_OPTIONS=
# enforce using portable C locale
LC_ALL=C
export LC_ALL GREP_OPTIONS

# function to create one style_*.h file

style () {
  list=`grep -sl $1 $2*.h`
  if (test -e style_$3.tmp) then
    rm -f style_$3.tmp
  fi
  for file in $list; do
    qfile="\"$file\""
    echo "#include $qfile" >> style_$3.tmp
  done
  if (test ! -e style_$3.tmp) then
    if (test ! -e style_$3.h) then
      touch style_$3.h
    elif (test "`cat style_$3.h`" != "") then
      rm -f style_$3.h
      touch style_$3.h
    fi
  elif (test ! -e style_$3.h) then
    mv style_$3.tmp style_$3.h
  elif (test "`diff --brief style_$3.h style_$3.tmp`" != "") then
    mv style_$3.tmp style_$3.h
  else
    rm -f style_$3.tmp
  fi
}

# function to create one style_*.cpp registration translation unit
# args: 1=CLASS macro 2=file prefix 3=style name 4=XxxStyle macro 5=base class
#       6=registry accessor 7=register function 8=one-arg creator (1/0)
#       9=extra include headers (space separated)
# the stylegen helper parses the XxxStyle(key,Class) markers into explicit
# add_builtin() calls and copies preprocessor directives inside the marker block
# through verbatim so build-config-dependent markers stay guarded.

stylesource () {
  list=`grep -sl "$1" $2*.h | LC_ALL=C sort`
  rm -f style_$3.cpp.tmp
  "$stylegen" source "$4" "$5" "$6" "$7" "$8" "$9" -- $list > style_$3.cpp.tmp

  if (test ! -e style_$3.cpp) then
    mv style_$3.cpp.tmp style_$3.cpp
  elif (test "`diff --brief style_$3.cpp style_$3.cpp.tmp`" != "") then
    mv style_$3.cpp.tmp style_$3.cpp
  else
    rm -f style_$3.cpp.tmp
  fi
}

# emit package_styles() entries for one category (all packages, enabled or not)
# args: 1=XxxStyle macro 2=file prefix 3=struct member

pkgentries () {
  list=`grep -sl "$1(" */$2*.h | LC_ALL=C sort`
  if (test -n "$list") then
    "$stylegen" package "$1" "$3" -- $list
  fi
}

# create the single package_registry.cpp (style keyword -> package name)

packageregistry () {
  rm -f package_registry.cpp.tmp
  {
    echo "// auto-generated by the LAMMPS build system from style markers. DO NOT EDIT."
    echo ""
    echo "#include \"package_registry.h\""
    echo ""
    echo "namespace LAMMPS_NS {"
    echo ""
    echo "void register_package_styles()"
    echo "{"
    pkgentries AngleStyle     angle_     angle_styles
    pkgentries AtomStyle      atom_vec_  atom_styles
    pkgentries BodyStyle      body_      body_styles
    pkgentries BondStyle      bond_      bond_styles
    pkgentries CommandStyle   ""         command_styles
    pkgentries ComputeStyle   compute_   compute_styles
    pkgentries DihedralStyle  dihedral_  dihedral_styles
    pkgentries DumpStyle      dump_      dump_styles
    pkgentries FixStyle       fix_       fix_styles
    pkgentries ImproperStyle  improper_  improper_styles
    pkgentries IntegrateStyle ""         integrate_styles
    pkgentries KSpaceStyle    ""         kspace_styles
    pkgentries MinimizeStyle  min_       minimize_styles
    pkgentries PairStyle      pair_      pair_styles
    pkgentries ReaderStyle    reader_    reader_styles
    pkgentries RegionStyle    region_    region_styles
    echo "}"
    echo ""
    echo "}    // namespace LAMMPS_NS"
  } > package_registry.cpp.tmp

  if (test ! -e package_registry.cpp) then
    mv package_registry.cpp.tmp package_registry.cpp
  elif (test "`diff --brief package_registry.cpp package_registry.cpp.tmp`" != "") then
    mv package_registry.cpp.tmp package_registry.cpp
  else
    rm -f package_registry.cpp.tmp
  fi
}

# create individual style files
# called by "make machine"
# col 1 = string to search for
# col 2 = search in *.h files starting with this name
# col 3 = name of style file
# col 4 = file that includes the style file
# col 5 = optional 2nd file that includes the style file

cmd=$1
objdir=$2

# location of the generated stylegen helper binary.  The Makefile passes the
# build's object directory (created before this script runs and removed together
# with it), so the helper rides along with Obj_* like DEPEND/fastdep.c and needs
# no separate clean-up rule.  Fall back to the current directory for a manual
# "sh Make.sh style" invocation without an object directory argument.
if (test -z "$objdir" -o ! -d "$objdir") then
  objdir=.
fi
stylegen="$objdir/stylegen.exe"

# only the array/mask-based categories still expand the XXX_CLASS macro at
# compile time and need a style_*.h include list.  The name-keyed categories are
# registered through the global registry from generated style_*.cpp (below).

if (test $cmd = "style") then

  $cmd NBIN_CLASS         nbin_          nbin          neighbor
  $cmd NPAIR_CLASS        npair_         npair         neighbor
  $cmd NSTENCIL_CLASS     nstencil_      nstencil      neighbor
  $cmd NTOPO_CLASS        ntopo_         ntopo         neighbor

fi

# generate style_*.cpp registration translation units for migrated categories
# args: CLASS prefix style XxxStyle base accessor regfunc one-arg "includes"

if (test $cmd = "style") then

  # build the portable style/registry generator (replaces awk for portability).
  # compiled with "cc" like DEPEND/fastdep.c, so it adds no new build dependency.
  cc -O -o "$stylegen" DEPEND/stylegen.c || exit 1

  stylesource PAIR_CLASS     pair_     pair     PairStyle     Pair     Force::pair_styles     register_pair_styles     1 "force.h pair.h"
  stylesource BOND_CLASS     bond_     bond     BondStyle     Bond     Force::bond_styles     register_bond_styles     1 "force.h bond.h"
  stylesource ANGLE_CLASS    angle_    angle    AngleStyle    Angle    Force::angle_styles    register_angle_styles    1 "force.h angle.h"
  stylesource DIHEDRAL_CLASS dihedral_ dihedral DihedralStyle Dihedral Force::dihedral_styles register_dihedral_styles 1 "force.h dihedral.h"
  stylesource IMPROPER_CLASS improper_ improper ImproperStyle Improper Force::improper_styles register_improper_styles 1 "force.h improper.h"
  stylesource KSPACE_CLASS   ""        kspace   KSpaceStyle   KSpace   Force::kspace_styles   register_kspace_styles   1 "force.h kspace.h"
  stylesource FIX_CLASS       fix_      fix       FixStyle       Fix       Modify::fix_styles       register_fix_styles       0 "modify.h fix.h"
  stylesource COMPUTE_CLASS   compute_  compute   ComputeStyle   Compute   Modify::compute_styles   register_compute_styles   0 "modify.h compute.h"
  stylesource INTEGRATE_CLASS ""        integrate IntegrateStyle Integrate Update::integrate_styles register_integrate_styles 0 "update.h integrate.h"
  stylesource MINIMIZE_CLASS  min_      minimize  MinimizeStyle  Min       Update::minimize_styles  register_minimize_styles  1 "update.h min.h"
  stylesource REGION_CLASS    region_   region    RegionStyle    Region    Domain::region_styles    register_region_styles    0 "domain.h region.h"
  stylesource DUMP_CLASS      dump_     dump      DumpStyle      Dump      Output::dump_styles      register_dump_styles      0 "output.h dump.h"
  stylesource COMMAND_CLASS   ""        command   CommandStyle   Command   Input::command_styles    register_command_styles   1 "input.h command.h"
  stylesource ATOM_CLASS      atom_vec_ atom      AtomStyle      AtomVec   Atom::avec_styles        register_atom_styles      1 "atom.h atom_vec.h"
  stylesource BODY_CLASS      body_     body      BodyStyle      Body      AtomVecBody::body_styles register_body_styles      0 "atom_vec_body.h body.h"
  stylesource READER_CLASS    reader_   reader    ReaderStyle    Reader    ReadDump::reader_styles  register_reader_styles    1 "read_dump.h reader.h"

  packageregistry

fi
