# Settings for libraries used by specific LAMMPS packages
# this file is auto-edited when those packages are included/excluded

PKG_INC =  -I../../lib/atc -I../../lib/reax -I../../lib/poems -I../../lib/meam 
PKG_PATH = -L../../lib/atc -L../../lib/reax -L../../lib/poems -L../../lib/meam 
PKG_LIB =  -latc -lreax -lpoems -lmeam 

PKG_SYSPATH = $(user-atc_SYSPATH) $(reax_SYSPATH) $(meam_SYSPATH) 
PKG_SYSLIB =  $(user-atc_SYSLIB) $(reax_SYSLIB) $(meam_SYSLIB) 
