# Create LAMMPS input files this way:
cd moltemplate_files

  # Run moltemplate with the "-allow-wildcards" and "-nocheck" arguments
  # as well as a custom -atomstyle

  moltemplate.sh -atomstyle "atomid atomtype flag density x y z" system.lt \
                 -allow-wildcards -nocheck

  # This will generate various files with names ending in *.in* and *.data.
  # Move them to the directory where you plan to run LAMMPS (in this case "../")
  mv -f system.data system.in* ../

  # Optional:
  # The "./output_ttree/" directory is full of temporary files generated by
  # moltemplate.  They can be useful for debugging, but are usually thrown away.
  rm -rf output_ttree/

cd ../
